# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08ba612741205a2f2e16d6ca5f4faa85d7b3dbf0e581edeeada38f93871df8b21e69dd8fe36c80bf0aa0a3be817509f34a2f5a04cdb6210ebf962f4cb0ef5d0e

test:
  secret_key_base: 1c6f4d1e870e26c7ccab8303c8fa158e091332bf4e1dd2a4af40e427f88fd2e3b05e8bd15678856df5fddbecd679520fb8950b49c47f086f9b7d870159345331

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
